[package]
name = "testcontainers"
version = "0.3.1"
authors = [ "CoBloX developers <team@coblox.tech>" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/coblox/testcontainers-rs"
categories = ["development-tools::testing"]
keywords = ["docker", "testcontainers"]
description = "Meta crate for testcontainers, a library for integration-testing against docker containers from within Rust."

[dependencies]
tc_core = { path = "../core", version = "0.2" }

# Clients
tc_cli_client = { path = "../cli_client", version = "0.1" }

# Images
tc_coblox_bitcoincore = { path = "../images/coblox_bitcoincore", version = "0.3" }
tc_trufflesuite_ganachecli = { path = "../images/trufflesuite_ganachecli", version = "0.3" }
tc_parity_parity = { path = "../images/parity_parity", version = "0.2" }

[dev-dependencies]
bitcoin_rpc_client = "0.4"
spectral = "0.6"
web3 = "0.5"
pretty_env_logger = "0.2"
